#ifndef	PB_MESSAGE_READER_HPP
#define	PB_MESSAGE_READER_HPP

#include <cstdint>
#include <functional>
#include <optional>
#include <stdexcept>
#include <utility>
#include <vector>

#include "pb.h"
#include "pb_decode.h"
#include "reader.hpp"

namespace nanoipc {
    /// @brief Deserializes Protocol Buffer messages from frame data.
    ///
    /// PbMessageReader reads encoded frame data using a Reader<std::vector<std::uint8_t>>,
    /// decodes it as a Protocol Buffer message of type Tpb_msg using nanopb, and provides
    /// the deserialized message via the Reader interface.
    ///
    /// @tparam Tpb_msg The protobuf message type (e.g., generated by nanopb).
    template <typename Tpb_msg>
	class PbMessageReader: public Reader<Tpb_msg> {
	public:
        /// @brief Callback type for initializing protobuf messages.
        using PbMessageInitializer = std::function<void(Tpb_msg *)>;

		/// @brief Construct a PbMessageReader.
		/// @param frame_reader Pointer to a Reader<std::vector<std::uint8_t>> that provides encoded frame data.
		///                     Must not be null.
		/// @param nanopb_message_fields Pointer to the nanopb message descriptor.
		///                             Must not be null.
		/// @param pb_message_initializer Optional callback to initialize the message before decoding.
		/// @throws std::invalid_argument if frame_reader or nanopb_message_fields is null.
		PbMessageReader(
            Reader<std::vector<std::uint8_t>> *frame_reader,
			const pb_msgdesc_t *nanopb_message_fields,
			const PbMessageInitializer& pb_message_initializer = nullptr
        ): m_frame_reader(frame_reader), m_nanopb_message_fields(nanopb_message_fields), m_pb_message_initializer(pb_message_initializer) {
			if (!m_frame_reader || !m_nanopb_message_fields) {
				throw std::invalid_argument("invalid arguments in PbMessageReader ctor");
			}
		}
		PbMessageReader(const PbMessageReader&) = default;
		PbMessageReader& operator=(const PbMessageReader&) = default;

		/// @brief Read and decode the next Protocol Buffer message.
		/// @return An optional containing the decoded message, or std::nullopt if no frame data is available.
		std::optional<Tpb_msg> read() override {
            const auto frame_data = m_frame_reader->read();
            if (!frame_data.has_value()) {
                return std::nullopt;
            }
            Tpb_msg pb_message;
			if (m_pb_message_initializer) {
				m_pb_message_initializer(&pb_message);
			}
			pb_istream_t istream = pb_istream_from_buffer(frame_data->data(), frame_data->size());
			if (!pb_decode(&istream, m_nanopb_message_fields, &pb_message)) {
				throw std::runtime_error(
					"failed to decode protocol buffer: " + std::string(PB_GET_ERROR(&istream))
				);
			}
            return std::make_optional(std::move(pb_message));
		}

	private:
        Reader<std::vector<std::uint8_t>> *m_frame_reader;
		const pb_msgdesc_t *m_nanopb_message_fields;
		PbMessageInitializer m_pb_message_initializer;
	};
}

#endif // PB_MESSAGE_READER_HPP